### ISSUE TITLE
widows 11 lsass注入失败

### ISSUE THREAD

**Issue by wgetnz** [whoami-juruo/InjectTools#1]
RT .  lsass有保护

**Comment by whoami-juruo** [comment]
能注，你是不是没过UAC
![屏幕截图 2024-07-30 010838](https://github.com/user-attachments/assets/1cba6277-276e-4ca0-a94b-c3bb854c8e83)

**Comment by whoami-juruo** [comment]
kes保护下注入不了

**Comment by lock778** [comment]
一起合作吗？
